#define max 10
int check(char str[10],int len2);
float calc(char s[10],double x);
int assign(double s1[],int top1,char x);
float secant();
float fu(float x);
int newraphson(void);
float fl(float x);
float df (float x);
int fixedp(void);
float G(float x);
float F(float x);
void trapi();
void simp();
float FL(float x);
int regularfalsi(void);
float fun(float x);
void newtfd();
void newtdd();
int factorial(int value);
int newtbd();
void leg();
float func(float);
int bisect();
void bisection (float *x, float a, float b, int *itr);
float funct(float x);
int gausse();
void dolittle();
double parsing();
void linreg();
int info();
void polyreg();
void compute(float x[max],float y[max],float c[max][max],float b[max],int n,int m);
void coeff(int n,float a[max][max],float b[max],float x[max]);
int infoleg();
int infoin();
int infotr();
int infosi();
int infos();
int infon();
int infof();
int infonbd();
int infonfd();
int infondd();
int infob();
int infor();
